### ISSUE TITLE
About EMPTY()

### ISSUE THREAD

**Issue by HernanCano** [RickCHodgin/libsf#25]
Hi, friends.
I consider that NULL values in VJr must be checked, for example: In VJr EMPTY() returns .T. if _VAR_TYPE_NULL, but "originally" it is not so: originally EMPTY() says .F.; I have not found ((yet)) any function that reaches NULLs except EMPTY(). In Chapter 9 the doc [[ http://www.visual-freepro.org/wiki/index.php/VXB  ]] talks about "VXB Supported Variables", but doesn't give enough info.
This is not critical for this moment: it can be called as an enhancement. We can say this in the doc.

But we must know how to compatibilize.

HERNAN CANO M.
Contributor VFrP / VJr

**Comment by RickCHodgin** [comment]
Fixed.  See:  https://github.com/RickCHodgin/libsf/commit/bbf98008da1ceb4505396dcf0f9fcd9065af2614
